{
 "title": "Kafka  Broker / Performance & Latency",
 "tags": [
  "kafka",
  "broker",
  "troubleshoot"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Envrionment",
    "query": "label_values(kafka_server_brokerstate, env)"
   },
   {
    "name": "instance",
    "label": "Broker Host",
    "query": "label_values(kafka_network_request_metrics_time_ms{env=\"$env\"}, instance)"
   },
   {
    "name": "request",
    "label": "Request Type",
    "query": "label_values(kafka_network_request_metrics_time_ms, request)"
   }
  ]
 },
 "panels": [
  {
   "title": "Request Latency : $request  ($instance)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "instance"
  },
  {
   "title": "Request Total Time Ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_network_request_metrics_time_ms{instance=~\"$instance\", request=~\"$request\", aggregate=~\"Mean\", scope=~\"Total\",env=\"$env\"}",
     "legendFormat": "{{instance}} / {{ aggregate}}"
    },
    {
     "expr": "kafka_network_request_metrics_time_ms{instance=~\"$instance\", request=~\"$request\", aggregate=~\"99thPercentile\", scope=~\"Total\",env=\"$env\"}",
     "legendFormat": "{{instance}} / {{ aggregate}}"
    },
    {
     "expr": "kafka_network_request_metrics_time_ms{instance=~\"$instance\", request=~\"$request\", aggregate=~\"75thPercentile\", scope=~\"Total\",env=\"$env\"}",
     "legendFormat": "{{instance}} / {{ aggregate}}"
    }
   ]
  },
  {
   "title": "Network Socket Avg Idle Percent",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "kafka_network_socket_server_processor_avg_idle_percent{instance=~\"$instance\",env=\"$env\"}"
    }
   ]
  },
  {
   "title": "Request Handler Avg Idle Percent",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "kafka_server_request_handler_avg_idle_percent{instance=~\"$instance\", aggregate=~\"OneMinuteRate\",env=\"$env\"}"
    }
   ]
  },
  {
   "title": "Requests Per Sec",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kafka_network_request_per_sec{aggregate=~\"OneMinuteRate\",instance=~\"$instance\",request=~\"$request\",env=\"$env\"}"
    }
   ]
  },
  {
   "title": "Response Queue Size",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kafka_network_request_channel_queue_size{instance=~\"$instance\", queue=~\"Response\",env=\"$env\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request Queue Size",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kafka_network_request_channel_queue_size{instance=~\"$instance\", queue=~\"Request\", env=\"$env\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request Queue Time(Ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_network_request_metrics_time_ms{instance=~\"$instance\", request=~\"$request\", aggregate=~\"Mean\", scope=~\"RequestQueue\",env=\"$env\"}",
     "legendFormat": "{{instance}} / {{aggregate}}"
    },
    {
     "expr": "kafka_network_request_metrics_time_ms{instance=~\"$instance\", request=~\"$request\", aggregate=~\"75thPercentile\", scope=~\"RequestQueue\",env=\"$env\"}",
     "legendFormat": "{{instance}} / {{aggregate}}"
    },
    {
     "expr": "kafka_network_request_metrics_time_ms{instance=~\"$instance\", request=~\"$request\", aggregate=~\"99thPercentile\", scope=~\"RequestQueue\",env=\"$env\"}",
     "legendFormat": "{{instance}} / {{aggregate}}"
    }
   ]
  },
  {
   "title": "Local Time(Ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_network_request_metrics_time_ms{instance=~\"$instance\", request=~\"$request\", aggregate=~\"Mean\", scope=~\"Local\",env=\"$env\"}",
     "legendFormat": "{{instance}} / {{aggregate}}"
    },
    {
     "expr": "kafka_network_request_metrics_time_ms{instance=~\"$instance\", request=~\"$request\", aggregate=~\"75thPercentile\", scope=~\"Local\",env=\"$env\"}",
     "legendFormat": "{{instance}} / {{aggregate}}"
    },
    {
     "expr": "kafka_network_request_metrics_time_ms{instance=~\"$instance\", request=~\"$request\", aggregate=~\"99thPercentile\", scope=~\"Local\",env=\"$env\"}",
     "legendFormat": "{{instance}} / {{aggregate}}"
    }
   ]
  },
  {
   "title": "Remote Time(Ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_network_request_metrics_time_ms{instance=~\"$instance\", request=~\"$request\", aggregate=~\"Mean\", scope=~\"Remote\",env=\"$env\"}",
     "legendFormat": "{{instance}} / {{aggregate}}"
    },
    {
     "expr": "kafka_network_request_metrics_time_ms{instance=~\"$instance\", request=~\"$request\", aggregate=~\"75thPercentile\", scope=~\"Remote\",env=\"$env\"}",
     "legendFormat": "{{instance}} / {{aggregate}}"
    },
    {
     "expr": "kafka_network_request_metrics_time_ms{instance=~\"$instance\", request=~\"$request\", aggregate=~\"99thPercentile\", scope=~\"Remote\",env=\"$env\"}",
     "legendFormat": "{{instance}} / {{aggregate}}"
    }
   ]
  },
  {
   "title": "Throttle Time(Ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_network_request_metrics_time_ms{instance=~\"$instance\", request=~\"$request\", aggregate=~\"Mean\", scope=~\"Throttle\",env=\"$env\"}",
     "legendFormat": "{{instance}} / {{aggregate}}"
    },
    {
     "expr": "kafka_network_request_metrics_time_ms{instance=~\"$instance\", request=~\"$request\", aggregate=~\"75thPercentile\", scope=~\"Throttle\",env=\"$env\"}",
     "legendFormat": "{{instance}} / {{aggregate}}"
    },
    {
     "expr": "kafka_network_request_metrics_time_ms{instance=~\"$instance\", request=~\"$request\", aggregate=~\"99thPercentile\", scope=~\"Throttle\",env=\"$env\"}",
     "legendFormat": "{{instance}} / {{aggregate}}"
    }
   ]
  },
  {
   "title": "Response Queue Time(Ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_network_request_metrics_time_ms{instance=~\"$instance\", request=~\"$request\", aggregate=~\"Mean\", scope=~\"ResponseQueue\",env=\"$env\"}",
     "legendFormat": "{{instance}} / {{aggregate}}"
    },
    {
     "expr": "kafka_network_request_metrics_time_ms{instance=~\"$instance\", request=~\"$request\", aggregate=~\"75thPercentile\", scope=~\"ResponseQueue\",env=\"$env\"}",
     "legendFormat": "{{instance}} / {{aggregate}}"
    },
    {
     "expr": "kafka_network_request_metrics_time_ms{instance=~\"$instance\", request=~\"$request\", aggregate=~\"99thPercentile\", scope=~\"ResponseQueue\",env=\"$env\"}",
     "legendFormat": "{{instance}} / {{aggregate}}"
    }
   ]
  },
  {
   "title": "Response Send Time(Ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_network_request_metrics_time_ms{instance=~\"$instance\", request=~\"$request\", aggregate=~\"Mean\", scope=~\"ResponseSend\",env=\"$env\"}",
     "legendFormat": "{{instance}} / {{aggregate}}"
    },
    {
     "expr": "kafka_network_request_metrics_time_ms{instance=~\"$instance\", request=~\"$request\", aggregate=~\"75thPercentile\", scope=~\"ResponseSend\",env=\"$env\"}",
     "legendFormat": "{{instance}} / {{aggregate}}"
    },
    {
     "expr": "kafka_network_request_metrics_time_ms{instance=~\"$instance\", request=~\"$request\", aggregate=~\"99thPercentile\", scope=~\"ResponseSend\",env=\"$env\"}",
     "legendFormat": "{{instance}} / {{aggregate}}"
    }
   ]
  },
  {
   "title": "Network Processor Idle Percent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "kafka_network_processor_idle_percent{instance=~\"$instance\",env=\"$env\"}",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  {
   "title": "Request Handler Avg Idle Percent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "kafka_server_request_handler_avg_idle_percent{instance=~\"$instance\", aggregate=~\"OneMinuteRate\",env=\"$env\"}",
     "legendFormat": "{{processor}}"
    }
   ]
  }
 ]
}